[package]

name = "zip"
version = "0.5.0"
authors = ["Mathijs van de Nes <git@mathijs.vd-nes.nl>"]
license = "MIT"
repository = "https://github.com/mvdnes/zip-rs.git"
documentation = "http://mvdnes.github.io/rust-docs/zip-rs/zip/index.html"
keywords = ["zip", "archive"]
description = """
Library to support the reading and writing of zip files.
"""

[dependencies]
time = { version = "0.1", optional = true }
podio = "0.1"
bzip2 = { version = "0.3", optional = true }
libflate = { version = "0.1.16", optional = true }
crc32fast = "1.0"
bytes = "0.4.11"
string = "0.1.2"

[dev-dependencies]
bencher = "0.1"
rand = "0.4"
walkdir = "1.0"

[features]
deflate = ["libflate"]
default = ["bzip2", "deflate", "time"]

[[bench]]
name = "read_entry"
harness = false
